name: PHP CI

on: [push, pull_request]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate PHP syntax
        run: find . -name '*.php' -exec php -l {} \;
